<a href="https://colab.research.google.com/github/kimthanhKBS/DATA5000/blob/main/week_3/week_3_1_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATA5000 Workshop #3 (neural network)

# Load python libraries

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.datasets import load_iris

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Load iris flower classification data set

In [ ]:
iris = load_iris()
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Clean and transform data

In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
y = iris.target            # MUST be 1-D
y = y.astype(int)

# Onehot Encoding

In [ ]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)
y

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# Split data into training and testing

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=123)

# Setup feed-forward neural network model

In [ ]:
# Create the model
model = Sequential()

# Add layers to the model
model.add(Dense(units=10, input_shape=(4,), activation='relu', name= 'fc1'))  # Input layer
model.add(Dense(units=10, activation='relu', name='fc2'))  # Hidden layer
model.add(Dense(units=3, activation='softmax', name='output'))  # Output layer

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Summary of the model
print('Neural Network Model Summary:')
model.summary()

Neural Network Model Summary:


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ fc1 (Dense)                          │ (None, 10)                  │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ fc2 (Dense)                          │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ output (Dense)                       │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

# Train model

In [ ]:
model.fit(train_x, train_y, verbose=2, epochs=200, batch_size=5)
# verbose=0: No output is displayed during training.
# verbose=2: Displays one line per epoch, summarizing the training process.
# epochs=200: the model will go through the training data 200 times.
# batch_size=5: the number of samples per gradient update，the model will update its weights after processing a batch of 5 samples.

Epoch 1/200
24/24 - 2s - 87ms/step - accuracy: 0.4083 - loss: 1.0430
Epoch 2/200
24/24 - 0s - 2ms/step - accuracy: 0.6750 - loss: 0.8912
Epoch 3/200
24/24 - 0s - 2ms/step - accuracy: 0.6750 - loss: 0.8168
Epoch 4/200
24/24 - 0s - 2ms/step - accuracy: 0.6750 - loss: 0.7582
Epoch 5/200
24/24 - 0s - 2ms/step - accuracy: 0.6750 - loss: 0.7018
Epoch 6/200
24/24 - 0s - 2ms/step - accuracy: 0.6750 - loss: 0.6556
Epoch 7/200
24/24 - 0s - 2ms/step - accuracy: 0.8000 - loss: 0.6146
Epoch 8/200
24/24 - 0s - 3ms/step - accuracy: 0.8750 - loss: 0.5800
Epoch 9/200
24/24 - 0s - 2ms/step - accuracy: 0.9083 - loss: 0.5494
Epoch 10/200
24/24 - 0s - 2ms/step - accuracy: 0.9333 - loss: 0.5227
Epoch 11/200
24/24 - 0s - 2ms/step - accuracy: 0.9417 - loss: 0.5009
Epoch 12/200
24/24 - 0s - 6ms/step - accuracy: 0.9583 - loss: 0.4801
Epoch 13/200
24/24 - 0s - 2ms/step - accuracy: 0.9250 - loss: 0.4624
Epoch 14/200
24/24 - 0s - 9ms/step - accuracy: 0.9167 - loss: 0.4480
Epoch 15/200
24/24 - 0s - 5ms/step - accur

# Predict results and evaluate model

In [ ]:
results = model.evaluate(test_x, test_y)
results

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 917ms/step - accuracy: 0.9000 - loss: 0.1122


[0.11216897517442703, 0.8999999761581421]